### ISSUE TITLE
Does ProcessTremolo() anything?

### ISSUE THREAD

**Issue by annplaksin** [music-encoding/sibmei#116]
I'm sorry for the stupid question, but I want to make sure, that I am not totally wrong...
Is it possible, that the function `ProcessTremolo()` isn't called anywhere in the latest version?

**Comment by th-we** [comment]
You're right. It looks like unfinished work in progress.

**Comment by annplaksin** [comment]
Okay, if it's unfinished work I will better not touch it...
In the case you'll plan to finish your work on that, I would like to mention, that other attributes would be necessary for a MEI 4.0 version for `<fTrem>`:
* @measperf -> @unitdur
* @slash -> @beams
But let's see how fast I will be with that work...

**Comment by th-we** [comment]
I don't mind you touching it (Andrew must have written it, but I don't think he'd mind either).

**Comment by ahankinson** [comment]
Nope, I don't mind.

**Comment by annplaksin** [comment]
Okay, but for now I find only the time to change the attributes...
Thanks for the kind answers!
