### ISSUE TITLE
Non-object error for scores with lyrics

### ISSUE THREAD

**Issue by schen18** [music-encoding/sibmei#125]
Encountering the below error for some scores with lyrics

SibMei/sibmei2::ProcessLyics48:Cannot call Method Push on a non-object

**Comment by th-we** [comment]
Can you attach an example file?

**Comment by schen18** [comment]
Here's one of the files that failed with the error. Thanks.

[Credo.zip](https://github.com/music-encoding/sibmei/files/3899613/Credo.zip)

**Comment by yeonoson** [comment]
I get the same problem with several .sib files, e.g. with https://www.liederindex.de/songs/5647/file/7141

The problem seems to be related with the line `lyricvoice[verse_num].Push(lyricObj);`. I tried to use `IsValid(lyricvoice[verse_num])` directly before the Push-call, but it seems to always return True.

**Comment by th-we** [comment]
Reduced test case:

[lyrics-crash.sib.zip](https://github.com/music-encoding/sibmei/files/4675580/lyrics-crash.sib.zip)

**Comment by th-we** [comment]
The current process of [determining the `verse_num` variable](https://github.com/music-encoding/sibmei/blob/ea6303b3ba4e09a752991d14f2088a0910dba44f/src/ExportProcessors.mss#L195) does not make a lot of sense right now – it only works for style IDs of the form `text.staff.space.hypen.lyrics.verse3`, will produce `@n='s'` for `text.staff.space.hypen.lyrics.chorus` and fails entirely for `text.staff.space.hypen.lyrics.above` as well as any custom lyrics styles.

@annplaksin I tagged this so we keep it in mind as a special case where project specific text styles should be taken into consideration.
