### ISSUE TITLE
Project specific Sibmei extensibility

### ISSUE THREAD

**Issue by th-we** [music-encoding/sibmei#161]
Because I plan to make an unusually large pull request, I wanted to announce this beforehand to you, @ahankinson and @rettinghaus in this issue.

@annplaksin and me worked on an [extension API](https://github.com/th-we/sibmei/blob/dev-extensions/Extensions.md) for Sibmei that allows the creation of project specific extensions of Sibmei without having to change Sibmei itself – to write plugins for the plugin, so to speak.  This currently allows custom handling of text styles and symbols that might be project specific.

@annplaksin wrote an extension based on this API for the [CMO](https://www.uni-muenster.de/CMO-Edition/cmo/cmo.html) as a proof that it actually works.  I plan to work to turn the extension API into a large pull request on Thursday or Friday.  (And I guess I could improve the documentation some more.)

**Comment by ahankinson** [comment]
Has this change been merged now?

**Comment by rettinghaus** [comment]
Yes. Fixed with #162
