### ISSUE TITLE
Specified natural signs not preserved

### ISSUE THREAD

**Issue by ahwitz** [music-encoding/sibmei#20]
http://132.206.14.122/chord-accids.mei and http://132.206.14.122/chord-accids.sib

Sibelius file includes explicitly specified naturals, these are not maintained in the MEI output even when they would be required musically (where att=func would not be "caution")

**Comment by ahankinson** [comment]
@ahwitz could you provide the chord-accids.sib file? It doesn't seem to be up anymore.

**Comment by ahwitz** [comment]
Seems like the machine's down, as I can't SSH to it or get the root directory of the webserver. Will resend an email to you in a sec that likely has it.
