### ISSUE TITLE
Accidentals in key signature still show up

### ISSUE THREAD

**Issue by mborsodi** [music-encoding/sibmei#24]
The accidentals in the mei files are always written as just accid, so they show up even when they are already in the key signature and don't actually need to.
I think this is also related to issue #20 with the natural signs not being written in, because natural signs don't show up when they cancel out the key signatures either.

**Comment by mborsodi** [comment]
[key signature sibelius file](https://github.com/DDMAL/mei-test-set/blob/develop/MEI-test-set/sibelius-files/repeats/second-time-difference.sib)

**Comment by ahankinson** [comment]
Fixed.
