### ISSUE TITLE
problem with grace note groupings

### ISSUE THREAD

**Issue by minamouse** [music-encoding/sibmei#25]
This is a problem that only comes up if there are multiple notes with grace notes in a single bar. 
If the first grace note in the bar is a single grace note, it works fine, but all the remaining grace notes, no matter what their original grouping was, get grouped together (with the right pitches, duration and order) onto the second note that contains a grace note. 
However, if the first grace note is a group of grace notes, all the rest in the bar appear on that first note right away.
![sibelius original](https://cloud.githubusercontent.com/assets/11529868/7736171/08ddb942-ff10-11e4-9e04-8ac2ec803625.png)
![verovio](https://cloud.githubusercontent.com/assets/11529868/7736172/0b2c808e-ff10-11e4-8cab-6d7fcdacdd60.png)

**Comment by ahankinson** [comment]
Please provide a link to the original Sibelius file as a reduction to the problem.

**Comment by mborsodi** [comment]
[grace notes sibelius file](https://github.com/DDMAL/mei-test-set/blob/develop/MEI-test-set/sibelius-files/grace-notes/grace-notes.sib)

**Comment by th-we** [comment]
Works in recent versions:

[multi-grace.sib.zip](https://github.com/music-encoding/sibmei/files/851209/multi-grace.sib.zip)

![bildschirmfoto vom 2017-03-17 17-38-58](https://cloud.githubusercontent.com/assets/1147152/24053237/afa715b2-0b38-11e7-8370-4fb3650c291d.png)
