### ISSUE TITLE
tuplets with rests

### ISSUE THREAD

**Issue by minamouse** [music-encoding/sibmei#26]
When tuplets have rests in them, sibmei groups all the notes to the front, puts the rest in the tuplet, and at the end of the group. 
![screen shot 2015-05-21 at 12 12 21 pm](https://cloud.githubusercontent.com/assets/11529868/7753371/01a3cdbc-ffb3-11e4-9b09-2f28e4c63e10.png)

However, it seems to only be an issue if there are beams on the notes, because when they're separate, it works fine.
![screen shot 2015-05-21 at 12 12 14 pm](https://cloud.githubusercontent.com/assets/11529868/7753386/1739f264-ffb3-11e4-852e-d37cc01e2def.png)

What's weird, though, is that it does the incorrect tuplet placement with normal tuplets (i.e. when there are no rests involved), but somehow not all the time, and I can't really tell when.
![screen shot 2015-05-21 at 12 18 53 pm](https://cloud.githubusercontent.com/assets/11529868/7753498/d52e6caa-ffb3-11e4-98a2-619aec42fc15.png)

**Comment by ahankinson** [comment]
Please provide a link to the original Sibelius file as a reduction to the problem.

**Comment by mborsodi** [comment]
[rests tuplet sibelius file](https://github.com/DDMAL/mei-test-set/blob/develop/MEI-test-set/sibelius-files/tuplets/tuplets-two-parts.sib)

**Comment by th-we** [comment]
Can this be closed now? Works for me.
