### ISSUE TITLE
clef changes

### ISSUE THREAD

**Issue by mborsodi** [music-encoding/sibmei#27]
It seems that when there are beams over clef changes, sibmei doesn't do it properly. It ends up grouping the changed clefs to the end of the beamed group.
(here, the clef should be changing every eighth note in the first half of each bar)
![screen shot 2015-05-21 at 4 14 47 pm](https://cloud.githubusercontent.com/assets/11529868/7758045/b3a28442-ffd4-11e4-965e-85494ce968f3.png)

**Comment by ahankinson** [comment]
Please provide a link to the original Sibelius file as a reduction to the problem.

**Comment by mborsodi** [comment]
[clef changes sibelius file](https://github.com/DDMAL/mei-test-set/blob/develop/MEI-test-set/sibelius-files/clefs/changing-clefs-7.sib)
