### ISSUE TITLE
problem with split secondary beams

### ISSUE THREAD

**Issue by minamouse** [music-encoding/sibmei#28]
There is a problem with the way sibmei encodes beaming. Specifically, secondary beams. 
Basically, what it seems to be doing is grouping the notes on which secondary beams begin to the end of the beamed group. 
So, when I input something like this into sibelius:
![screen shot 2015-05-22 at 9 31 30 am](https://cloud.githubusercontent.com/assets/11529868/7771568/45434d00-0066-11e5-942d-b042aa1b5438.png)

sibmei turns it into this:
![screen shot 2015-05-22 at 9 31 35 am](https://cloud.githubusercontent.com/assets/11529868/7771570/499680de-0066-11e5-989e-96c5df30f306.png)

Another example:
![screen shot 2015-05-22 at 9 29 51 am](https://cloud.githubusercontent.com/assets/11529868/7771598/71b8b0be-0066-11e5-913a-651a5f9d84b0.png)
![screen shot 2015-05-22 at 9 29 56 am](https://cloud.githubusercontent.com/assets/11529868/7771597/71b663a4-0066-11e5-8564-86639d06165a.png)

**Comment by ahankinson** [comment]
Please provide a link to the original Sibelius file as a reduction to the problem.

**Comment by mborsodi** [comment]
[beaming sibelius file](https://github.com/DDMAL/mei-test-set/blob/develop/MEI-test-set/sibelius-files/additional-tests/beam-test.sib)

**Comment by th-we** [comment]
Problem has shifted: Primary beams are now encoded correctly, but `@breaksec` should be set to mark secondary beam splits.

**Comment by th-we** [comment]
Works now:

[split-secondary-beams.sib.zip](https://github.com/music-encoding/sibmei/files/851220/split-secondary-beams.sib.zip)

![bildschirmfoto vom 2017-03-17 17-42-56](https://cloud.githubusercontent.com/assets/1147152/24053408/3fee7426-0b39-11e7-9935-ca4a5fbefc94.png)
