### ISSUE TITLE
quadruple dots

### ISSUE THREAD

**Issue by minamouse** [music-encoding/sibmei#32]
I don't actually know if it's even possible to fix this, because it's mostly sibelius' fault I think, but quadruple dots don't show up in the mei files.
The problem is that sibelius only allows up to 3 dots on notes, so if you want any more, you have to get the symbol that looks like it and add it as the fourth dot, then hide a rest to make it look right. It's a weird work around, that makes the mei files end up with 

``` xml
<note dots="3" dur="2" dur.ges="960p" oct="4" pname="g" xml:id="p1cgd4n0v1b2s1"/>
<space dur="32" dur.ges="32p" xml:id="p1r960v1b2s1"/>
<note dur="32" dur.ges="32p" oct="4" pname="g" xml:id="p1cgd4n992v1b2s1"/>
```

in [this](https://github.com/DDMAL/mei-test-set/blob/develop/MEI-test-set/MEI/meter/quadruple-dotted.mei) file, which is technically right considering what we put into sibelius, but not actually what we wanted.

**Comment by rettinghaus** [comment]
I guess, this won't be possible to fix. As this is a very special case, you should use a XSLT to fix the exported file (or do it manually).
