### ISSUE TITLE
changed stem directions

### ISSUE THREAD

**Issue by mborsodi** [music-encoding/sibmei#33]
When we change the stem direction in a sibelius file, it doesn't show up as `stem.dir="up"`, like you'd expect, so the stems go back to their default positions in verovio.

**Comment by ahankinson** [comment]
Could you link to a reduction of this please? I think stem.dir is encoded, but would need to see a specific instance where it is not.

**Comment by mborsodi** [comment]
Right. Here's the [mei file](https://github.com/DDMAL/mei-test-set/blob/develop/MEI-test-set/MEI/beams-and-stems/stem-directions-2.mei) and here's the sibelius original:
![screen shot 2015-06-18 at 11 04 12 am](https://cloud.githubusercontent.com/assets/11529868/8234412/cafe62b0-15a9-11e5-9436-f7ed55a5e0df.png)

**Comment by ahankinson** [comment]
Fixed in a280f1cf04bce08a1869654262bc5e97409ec0a7
