### ISSUE TITLE
beams over multiple rests

### ISSUE THREAD

**Issue by minamouse** [music-encoding/sibmei#35]
I think it sometimes does work, but [here](https://github.com/DDMAL/mei-test-set/blob/develop/MEI-test-set/MEI/meter/beams-over-rests.mei) for example, the multiple rests don't end up in beams somehow.

**Comment by th-we** [comment]
@minamouse, the uploaded file does not work any more - did you mean something like this?

[beamed-rests.sib.zip](https://github.com/music-encoding/sibmei/files/851228/beamed-rests.sib.zip)

![bildschirmfoto vom 2017-03-17 17-46-08](https://cloud.githubusercontent.com/assets/1147152/24053557/ba2624be-0b39-11e7-84e9-ed9d6f98890a.png)

If so, can you close this issue?

**Comment by ahankinson** [comment]
This is the specific test case she was talking about:

http://ddmal.github.io/mei-test-set/MEI-test-set/meter.html#beams-over-rests.mei

And yes, it seems to work now so I will close.
