### ISSUE TITLE
Ties with chords with attributes

### ISSUE THREAD

**Issue by lpugin** [music-encoding/sibmei#39]
It seems that the attribute tie with chords are wrong. SibMEI puts value "i" only for one note in the first tied chord and them "m". All notes should have the value "i" and similarly all notes should have "t" in the last tied chord. See example ties-chords-2 in the MEI test-set

**Comment by ahankinson** [comment]
In the latest version it doesn't even do this! I don't think any ties are exported. I'll have a look at it now.

**Comment by ahankinson** [comment]
This has been fixed in 2.0.0.
