### ISSUE TITLE
Bug in sibmei-2.0.0-beta3

### ISSUE THREAD

**Issue by efreja** [music-encoding/sibmei#40]
Hello,

I got the error with sibmei-2.0.0-beta3:

mei/sibmei2::GenerateLine:27:Field octl not found

It probably comes from the line:

line = libmei.Octave();

that should be replaced by:

octl = libmei.Octave();

Regards

**Comment by ahankinson** [comment]
Thanks! I have fixed it in the latest development code, so it will be in the next release.
