### ISSUE TITLE
Export to .mei with sibmei-1.4 in Sibelius 8.2

### ISSUE THREAD

**Issue by musicus** [music-encoding/sibmei#41]
After trying to export a MusicXML file to ```.mei``` in Siblius with the stable release plug-in ```sibmei-1.4``` I get the following (error) message in Sibelius 8.2: 

![screen shot 2016-04-04 at 12 41 20 pm](https://cloud.githubusercontent.com/assets/1203470/14255578/a8e0af46-fa62-11e5-8780-0a28a5343b7e.png)

There are no problems using the ```2.0.0-beta3``` version of the plug-in in Sibelius 8.2.

**Comment by ahankinson** [comment]
Since 1.x will not be supported going forward, I will close this.
