### ISSUE TITLE
Octave designation

### ISSUE THREAD

**Issue by karend27** [music-encoding/sibmei#42]
Hi Andrew,
I'm not sure if this is just a Sibelius issue or if it's something that's happening in the Sib to MEI export. Some of voice parts are in the wrong octave. It looks like it is in all the @oct attributes of note, and I think it's happening to voice parts that I changed the clef on (some I originally had in treble clef and changed to tenor, and had to transpose up down an octave to make them look correct in Sibelius). I saw the error when I tried to open the mei files in Laurent's MEI viewer. Looks like I can't attach MEI or Sib files here so I'll email you the MEI file where the motetus and tenor (voice 3 and 4) are in the wrong octave in the MEI version (though I changed the @oct attribute of the motetus first note to show where it's supposed to be); and the Sibelius file.
Thanks
Karen

**Comment by ahankinson** [comment]
Could you send me the file where you're seeing this issue?

**Comment by karend27** [comment]
It was a Sibelius problem. In order to properly change clefs in parts, you need to Change instrument and then transpose the part down an octave. I just changed the clefs instead of changing the instrument.
