### ISSUE TITLE
One tuplet encoded as multiple <tuplet> elements

### ISSUE THREAD

**Issue by martha-thomae** [music-encoding/sibmei#45]
Some tuplets in the Sibelius file are encoded as multiple <tuplet> elements in the mei file, instead of just one <tuplet> element.

When the base of a tuplet is ‘2’, if its numerator is greater than 3; the tuplet is encoded as more than one <tuplet> element in the mei file. Compare measures 4 and 6 to measure 2 in “tuplets_1”.

I think that this can be the cause that certain tuplets even get merged together sometimes, as in measure 8 of “tuplets_1” and measures 1 and 2 of “tuplets_2”; in the latter, this merge of tuplets even change the order of the notes.

[tuplet_issues.zip](https://github.com/music-encoding/sibmei/files/410020/tuplet_issues.zip)

**Comment by ahankinson** [comment]
I can't open this because it was created with a newer version of Sibelius. Could you please save so that it's compatible with version 7 of Sibelius? Thanks.

**Comment by martha-thomae** [comment]
Here, exported so it is compatible with Sibelius 7.

[tuplet_issues.zip](https://github.com/music-encoding/sibmei/files/411900/tuplet_issues.zip)

**Comment by ahankinson** [comment]
Fixed in 2365518efcd2bd1f1319407d9de6e9fed5a1323d

**Comment by martha-thomae** [comment]
Thank you Andrew :)
