### ISSUE TITLE
Performed duration (@dur.ges) isn't affected by <tuplet>

### ISSUE THREAD

**Issue by martha-thomae** [music-encoding/sibmei#46]
The performed duration (@dur.ges value) of a note inside a <tuplet> element, is not affected by the tuplet. In other words, a note inside a <tuplet>has the same performed value that a note outside of a tuplet.

Here is an example:
You can see that both eighth notes, inside and outside the tuplet, have a @dur.ges = "128p".
The same with the quarter notes, they have a @dur.ges = "256p", independently of them being inside or outside the <tuplet>.
[performed-duration_issue.zip](https://github.com/music-encoding/sibmei/files/430977/performed-duration_issue.zip)

**Comment by th-we** [comment]
@ahankinson I guess this can be closed, or does your commit still have some shortcomings that need to be addressed?

**Comment by martha-thomae** [comment]
Thanks!

**Comment by ahankinson** [comment]
Nope, should be fixed now.
