### ISSUE TITLE
Documentation concerning tests

### ISSUE THREAD

**Issue by th-we** [music-encoding/sibmei#71]
I'm not sure how to run the tests.  I checked out, built and installed [sib-test](https://github.com/tido/sib-test) and it shows up in the Edit Plugins window. I'm not sure, however, what else needs to be done to run the Testsibmei2 plugin without the error `Method Suite not found`.

If I'm not missing something obvious, I'd kindly ask for the Readme to be updated.

**Comment by rettinghaus** [comment]
@th-we may this be closed?

**Comment by th-we** [comment]
@rettinghaus Yes, it can. Thanks for spring cleaning ;-).
