### ISSUE TITLE
Insert page break at beginning of section

### ISSUE THREAD

**Issue by sonovice** [music-encoding/sibmei#86]
According to @lpugin , it is common TEI practice to include a page break element at the beginning of ~~a~~ the very first `<section>`. Maybe it would be sensible to do this in the export process as well?

See https://github.com/rism-ch/verovio/issues/728

**Comment by th-we** [comment]
IMO that's not appropriate.  A section can start anywhere on the page, look e.g. at [this example](https://github.com/th-we/sample-encodings/blob/master/MEI%203.0/Music/Complete%20examples/Marney_BreakThouTheBreadOfLife.mei#L498) where a section starts in the middle of line one.  Maybe there is a misunderstanding?

As Sibmei currently only generates a single section, we could of course add a page break at the beginning of the section, if that's what you mean.

**Comment by lpugin** [comment]
I did not mean to have a `<pb/>` a the beginning of each `<section>`, but there is the need to have one at the beginning of the first section.

**Comment by sonovice** [comment]
I'm sorry for the confusion, was a bit in a rush today. What I meant is having a `<pb/>` at the beginning of the very first `<section>`, thanks for pointing that out, Thomas and Laurent.

**Comment by th-we** [comment]
O.K., that's not a problem. I will implement this.

**Comment by th-we** [comment]
I added this in e4bb2a6.  Here's the compiled plugin:

[sibmei-leading-pb.zip](https://github.com/music-encoding/sibmei/files/1531781/sibmei-leading-pb.zip)

Does that work for you, @sonovice?

**Comment by sonovice** [comment]
Yes, thanks a lot!
