### ISSUE TITLE
When exporting tuplets, verse syllables get messed up

### ISSUE THREAD

**Issue by karend27** [music-encoding/sibmei#87]
This seems to often (always?) happen with a tuplet of three of more, with verse syllables under each note. In Sibelius the syllables are placed under each note, but in the export, the final note doesn't get a syllable, and the extra syllable is placed under a previous note (i.e., one note of the tuplet receives two syllables). Here's a screenshot of the code:

**Comment by karend27** [comment]
<img width="980" alt="screen shot 2018-05-06 at 10 32 10" src="https://user-images.githubusercontent.com/11195203/39674373-d4d9a120-5118-11e8-9ecd-ce59352a083a.png">

**Comment by th-we** [comment]
@karend27 Can you check if that's still a problem for you, and if so, supply a reduced test file that demonstrates the problem? I just tried and the problem seems to be gone.

**Comment by karend27** [comment]
Hi - I actually think this is a fixed problem. Is that true @martha-thomae ?
