### ISSUE TITLE
Performed duration of a note within <tuplet> has a larger value than outside <tuplet>

### ISSUE THREAD

**Issue by martha-thomae** [music-encoding/sibmei#90]
The performed duration (`@dur.ges`) of a note has a larger value when it is part of a `<tuplet>` than when it stands alone, which I think is opposite of the expected behaviour. Here I give an example.

[performed-duration.zip](https://github.com/music-encoding/sibmei/files/2099744/performed-duration.zip)

As you can see in this example, the quarter notes have a `@dur.ges="256p"` and the eighth notes have a `@dur.ges="128p"` when they are not part of a `<tuplet>`. However, when these notes are children of the `<tuplet>` element they performed duration increases to `@dur.ges="384p"` for the quarter note and `@dur.ges="129p"` for the eighth note. I believe the correct values would be `@dur.ges="171p"` for the quarter note and `@dur.ges="85p"` for the eighth note since now there are three notes in the place of two (given that `<tuplet @num="3" @numbase="2">`).

I think this is due to the **line 953** in `src/ExportGenerators.mss`:
`floatgesdur = (pnum & '.0' / pden & '.0') * dur;`
which I believe should be the other way around:
`floatgesdur = (pden & '.0' / pnum & '.0') * dur;`

What are your thoughts?
I can make the change and the pull request if you agree.

**Comment by ahankinson** [comment]
That sounds reasonable. Good job catching that! Please file a PR.
